## 05. Random Forest

Random Forest, en este caso, es un método de clasificación que utiliza un conjunto de muchos árboles de decisión diferentes. En este método, la decisión de clasificar en una clase u otra proviene de hacer la media de los resultados de todos los árboles de decisión. Random Forest tiene una pequeña variación y es difícil tener un sobreajuste. Usamos este método porque un árbol de decisión único es muy inestable y, por esa razón, entrenamos el modelo con muchos árboles de decisión.

In [1]:
# Libraries

import numpy as np
import pandas as pd

# Plots

import matplotlib
from matplotlib import pyplot as plt 
import seaborn as sns 

# Metricas

from scipy import stats as sts # normality test JB 
from sklearn import model_selection, linear_model, metrics
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split # split data
from sklearn.metrics import mean_squared_error # MSE
from sklearn.preprocessing import StandardScaler 
from sklearn import preprocessing # estandarization
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import KNNImputer
import pickle
from math import sqrt # sqrt
import itertools # aplanar arrays
import math

import random
random.seed(12345)

In [2]:
de_set = '../data/DE_set.csv'

In [3]:
prestamo = pd.read_csv(de_set)

In [4]:
prestamo.head(10)

,id,loan_amnt,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,...,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,application_type_Individual,application_type_Joint App,grade_y
0,0.999952,0.033333,0.027792,0.001124,0.021632,0.000000,0.216216,0.215054,0.2,0.206781,...,0,0,0,0,0,0,0,1,0,4
1,0.998648,0.384615,0.195791,0.010562,0.025636,0.000000,0.297297,0.295699,0.0,0.206781,...,0,0,0,0,0,0,0,1,0,4
2,0.999961,0.128846,0.105870,0.005208,0.008889,0.000000,0.216216,0.215054,0.0,0.206781,...,0,0,0,0,0,0,0,1,0,4
3,0.999979,0.497436,0.368578,0.004944,0.027087,0.000000,0.540541,0.537634,0.2,0.206781,...,0,0,0,0,0,0,0,1,0,5
4,0.999979,0.307692,0.237680,0.009551,0.006797,0.052632,0.000000,0.000000,0.0,0.099379,...,0,0,0,0,0,0,0,1,0,5
5,0.998111,0.282051,0.209468,0.007865,0.018358,0.000000,0.054054,0.053763,0.0,0.217391,...,0,0,0,0,0,0,0,1,0,5
6,0.997930,0.128205,0.097455,0.004169,0.030661,0.000000,0.108108,0.107527,0.0,0.434783,...,1,0,0,0,0,0,0,1,0,5
7,0.999273,0.282051,0.151316,0.007843,0.031461,0.000000,0.162162,0.161290,0.2,0.206781,...,0,0,0,0,0,0,0,1,0,4
8,0.996393,0.271154,0.194791,0.017191,0.017007,0.000000,0.324324,0.322581,0.0,0.149068,...,0,0,0,0,0,0,0,1,0,6
9,0.997252,0.497436,0.226802,0.012360,0.011081,0.000000,0.648649,0.645161,0.2,0.248447,...,0,0,0,0,0,0,0,1,0,6

### Creamos el Modelo de Random Forest

Ahora cargamos las variables de las 101 columnas de entrada en X excluyendo la columna “estado_prestamo” con el método drop(). En cambio agregamos la columna “estado_prestamo” en la variable y. Ejecutamos X.shape para comprobar la dimensión de nuestra matriz con datos de entrada de 475 registros por 101 columnas.

In [5]:
X = prestamo.drop('estado_prestamo', axis = 1)
y = prestamo['estado_prestamo']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 12345)

Y creamos nuestro modelo y hacemos que se ajuste (fit) a nuestro conjunto de entradas X y salidas ‘y’.

In [6]:
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

Y confirmamos cuan bueno fue nuestro modelo utilizando model.score() que nos devuelve la precisión media de las predicciones, en nuestro caso del 92,63%.

In [7]:
classifier.score(X_test, y_test)

0.9173157894736842

Si entrenamos el modelo con 100.000 variables, la precisión del modelo, baja a 91,73%.